# Generated by Django 2.2.4 on 2019-08-28 16:20

import areas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('polygon', areas.models.PolygonField(max_length=500)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.Provider')),
            ],
        ),
    ]
